# Generated by Django 6.0.2 on 2026-02-16 04:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoommateSelection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('verified', 'Verified')], default='draft', max_length=20)),
                ('verification_code', models.CharField(max_length=2)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roommate_selections', to='core.player')),
                ('roommate_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_by_as_1', to='core.player')),
                ('roommate_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_by_as_2', to='core.player')),
                ('roommate_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_by_as_3', to='core.player')),
                ('selection_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='core.selectionlink')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
