# Generated by Django 6.0.2 on 2026-02-21 13:58

from django.db import connection, migrations, models


def forwards_func(apps, schema_editor):
    """Apply collation only for PostgreSQL."""
    if connection.vendor == 'postgresql':
        schema_editor.execute(
            'ALTER TABLE core_player ALTER COLUMN name TYPE VARCHAR(255) COLLATE "is_IS"'
        )


def reverse_func(apps, schema_editor):
    """Remove collation only for PostgreSQL."""
    if connection.vendor == 'postgresql':
        schema_editor.execute(
            'ALTER TABLE core_player ALTER COLUMN name TYPE VARCHAR(255)'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_make_phone_email_optional'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
